### ISSUE TITLE
shameless plug

### ISSUE THREAD

**Issue by kguzek** [FloncDev/advent-of-code#1]
> Planning on making a CLI to get the inputs - cache them - and return them via stdout so that running can be made simple. Couldn't find anything like that which works so guess I got to do it myself.

If you've not got around to making it yourself, I made something similar to what you're describing for this year's AOC.

https://github.com/kguzek/advent-of-code-2024

It has an automatic solution template generator and saves your user-specific input to a file called `input.txt`. The solution comes pre-filled with a utility function which reads and parses the input file.

You can also add a `input-small.txt` to the solution directory, paste in the smaller examples from the problem descriptions, and the script will automatically use that input instead.

Since this year's AOC has ended, maybe you'll revisit or use it again next year ;) 

- Konrad (from silly selkies game jam 2022)

**Comment by FloncDev** [comment]
lmao did not expect to see an issue on here, especially not from an ex-codejamer :). Will make sure to check it out for next year - or hopefully finishing the rest of the 2024 ones...

Merry Christmas and happy new year btw

**Comment by kguzek** [comment]
you too!
